pipelines:
  branches:
    master:
      - step:
          name: Test
          image: javiersantos/android-ci:latest
          caches:
            - gradle
          script:
            - export GRADLE_USER_HOME=`pwd`/.gradle
            - ./gradlew writeDummySecrets test
