pipelines:
  branches:
    master:
      - step:
          name: Test
          image: bitbucketpipelines/android-ci-image
          caches:
            - gradle
          script:
            - yes | sdkmanager --licenses
            - chmod +x gradlew
            - ./gradlew test
