pipelines:
  branches:
    master:
      - step:
          name: Test
          image: bitbucketpipelines/android-ci-image
          caches:
            - gradle
          script:
            - ls -la $ANDROID_HOME/tools/bin
            - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
            - chmod +x gradlew
            - ./gradlew test
